### ISSUE TITLE
Unresolved imports in dependencies of "basic-applet"

### ISSUE THREAD

**Issue by ljfp** [bhh32/tutorials#1]
I tried to follow your tutorial on https://bhh32.com/posts/tutorials/cosmic_applet_tutorial but I think there were some changes on the libcosmic library since several imports are not working anymore.

These are the errors I get when trying to compile the project:

```
unresolved import `cosmic::iced_style`
could not find `iced_style` in `cosmic`
```

```
failed to resolve: could not find `wayland` in `iced`
could not find `wayland` in `iced
```

```
unresolved import `cosmic::iced::Command`
consider importing this struct instead:
std::process::Command
```

Those three errors came from here -> https://github.com/bhh32/tutorials/blob/main/rust/basic-applet/src/window.rs#L1-L11

Then there's this issue:

```
no associated item named `MAIN` found for struct `cosmic::iced::window::Id` in the current scope
associated item not found in `Id`
```

on line https://github.com/bhh32/tutorials/blob/main/rust/basic-applet/src/window.rs#L109 but this is probably related with the above problem when importing cosmic::iced_style

Finally, there's this issue:

`this function takes 1 argument but 3 arguments were supplied`

on line https://github.com/bhh32/tutorials/blob/main/rust/basic-applet/src/window.rs#L153

**Comment by bhh32** [comment]
Thank you for reporting this! I will go through and fix it and let you know when it's complete. Hopefully, I'll get it done fairly quickly.

**Comment by bhh32** [comment]
> I tried to follow your tutorial on https://bhh32.com/posts/tutorials/cosmic_applet_tutorial but I think there were some changes on the libcosmic library since several imports are not working anymore.
> 
> 
> 
> These are the errors I get when trying to compile the project:
> 
> 
> 
> ```
> 
> unresolved import `cosmic::iced_style`
> 
> could not find `iced_style` in `cosmic`
> 
> ```
> 
> 
> 
> ```
> 
> failed to resolve: could not find `wayland` in `iced`
> 
> could not find `wayland` in `iced
> 
> ```
> 
> 
> 
> ```
> 
> unresolved import `cosmic::iced::Command`
> 
> consider importing this struct instead:
> 
> std::process::Command
> 
> ```
> 
> 
> 
> Those three errors came from here -> https://github.com/bhh32/tutorials/blob/main/rust/basic-applet/src/window.rs#L1-L11
> 
> 
> 
> Then there's this issue:
> 
> 
> 
> ```
> 
> no associated item named `MAIN` found for struct `cosmic::iced::window::Id` in the current scope
> 
> associated item not found in `Id`
> 
> ```
> 
> 
> 
> on line https://github.com/bhh32/tutorials/blob/main/rust/basic-applet/src/window.rs#L109 but this is probably related with the above problem when importing cosmic::iced_style
> 
> 
> 
> Finally, there's this issue:
> 
> 
> 
> `this function takes 1 argument but 3 arguments were supplied`
> 
> 
> 
> on line https://github.com/bhh32/tutorials/blob/main/rust/basic-applet/src/window.rs#L153
> 
> 

This has been fixed here in the repo and the website. Thank you again for reporting it.
